# Generated by Django 4.1.4 on 2022-12-27 09:23

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='Username')),
                ('user_password', models.CharField(blank=True, max_length=200, verbose_name='Password')),
                ('user_fname', models.CharField(max_length=200, verbose_name='First name')),
                ('user_lname', models.CharField(max_length=200, verbose_name='Last name')),
                ('user_initial', models.CharField(max_length=1, verbose_name='Middle initial')),
                ('user_email', models.EmailField(max_length=200, unique=True, verbose_name='Work email address')),
                ('user_pnumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('user_image', models.ImageField(default='profile_pic/image.png', upload_to=users.models.image_path)),
                ('user_type', models.CharField(choices=[('Job Seeker', 'Job Seeker'), ('Job Provider', 'Job Provider')], max_length=100, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 12, 27, 9, 23, 45, 738080, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
