# Generated by Django 4.1.4 on 2022-12-27 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_pub_date_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 9, 29, 11, 9522, tzinfo=datetime.timezone.utc)),
        ),
    ]
