# Generated by Django 4.1.4 on 2022-12-28 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_type_user_type_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 0, 16, 49, 336805, tzinfo=datetime.timezone.utc)),
        ),
    ]
