# Generated by Django 4.1.4 on 2022-12-28 00:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='user_type',
            field=models.CharField(choices=[('Job Seeker', 'Job Seeker'), ('Job Provider', 'Job Provider')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 0, 25, 23, 589400, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.type'),
        ),
    ]
