# Generated by Django 4.1.4 on 2022-12-28 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_pub_date_alter_user_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 9, 19, 20, 981648, tzinfo=datetime.timezone.utc)),
        ),
    ]
