# Generated by Django 4.1.4 on 2022-12-28 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_pub_date_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 12, 45, 49, 807008, tzinfo=datetime.timezone.utc)),
        ),
    ]
