# Generated by Django 4.1.4 on 2022-12-28 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_pub_date_alter_user_user_type_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 13, 1, 1, 449059, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
